name: Pre-release package

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Build Windows executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: bpc.exe
        path: src/dist/windows
  
  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: bpc
        path: src/dist/linux



  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: [build-windows, build-linux]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bpc
      - uses: actions/download-artifact@v2
        with:
          name: bpc.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
              bpc
              bpc.exe
