name: Release package

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build Windows executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: bpc.exe
        path: src/dist/windows
  
  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: bpc
        path: src/dist/linux



  tagged-release:
    name: "Taggerd Release"
    runs-on: "ubuntu-latest"
    needs: [build-windows, build-linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bpc
      - uses: actions/download-artifact@v3
        with:
          name: bpc.exe
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false 
          files: |
              bpc
              bpc.exe
